apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/front
      context: ./front
      docker:
        buildArgs:
          app_api: http://bootcamp-demo.toolchain.lead.sandbox.liatr.io:3000/api
    - image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/back
      context: ./back
deploy:
  helm:
    releases:
      - name: realworld
        namespace: dob-realworld
        chartPath: ./conduit
        setValues:
          front.image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/front
          back.image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/back
