apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/front
      context: ./front
    - image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/back
      context: ./back
deploy:
  helm:
    releases:
      - name: realworld
        namespace: dob-realworld
        chartPath: ./conduit
        values:
          front.image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/front
          back.image: 774051255656.dkr.ecr.us-east-1.amazonaws.com/dob/back
