apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: node
    spec:
      containers:
      - image: {{ .Values.back.image }}
        imagePullPolicy: IfNotPresent
        name: node
        ports:
        - containerPort: 3000
      restartPolicy: Always
