apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: react
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: react
    spec:
      containers:
      - image: {{ .Values.front.image }}
        imagePullPolicy: IfNotPresent
        name: react
        ports:
        - containerPort: 4100
        env:
        - name: REACT_APP_API
          value: {{ .Values.backend_api }}
      restartPolicy: Always
